application: luckyordrin
version: 1
runtime: python27
api_version: 1
threadsafe: yes 
handlers:
- url: /src
  static_dir: src 


- url: /
  static_files: index.html
  upload: index.html

- url: .*
  script: index.app
